name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  YARN_ENABLE_GLOBAL_CACHE: false

jobs:
  chore:
    name: "Testing chores"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8  # v5.0.0

      - uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444  # v5.0.0
        with:
          node-version: lts/*

      - name: Get the Yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "dir=$(corepack yarn config get cacheFolder)" >> "$GITHUB_OUTPUT"

      - uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830  # v4.3.0
        with:
          path: ${{steps.yarn-cache-dir-path.outputs.dir}}
          key: ${{runner.os}}-yarn-${{hashFiles('**/yarn.lock')}}
          restore-keys: |
            ${{runner.os}}-yarn-

      - run: corepack yarn install --immutable

      - name: "Check for type errors"
        run: corepack yarn typecheck

      - name: "Check for linting errors"
        run: corepack yarn lint --max-warnings=0

  build-and-test:
    strategy:
      fail-fast: false
      matrix:
        node:
          - 20
          - 22
          - 24
        platform:
          - ubuntu-latest
          - macos-latest
          - windows-latest

      # Temporarily skipping Node.js 24 under Windows due to issue
      # https://github.com/nodejs/corepack/issues/715
      # vitest fails "handle integrity checks" on Windows with Node.js 24.x
        exclude:
          - node: 24
            platform: windows-latest

    name: "${{matrix.platform}} w/ Node.js ${{matrix.node}}.x"
    runs-on: ${{matrix.platform}}

    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8  # v5.0.0

      - name: "Use Node.js ${{matrix.node}}.x"
        uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444  # v5.0.0
        with:
          node-version: ${{matrix.node}}.x

      - name: Get the Yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "dir=$(corepack yarn config get cacheFolder)" >> "$GITHUB_OUTPUT"

      - uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830  # v4.3.0
        with:
          path: ${{steps.yarn-cache-dir-path.outputs.dir}}
          key: ${{runner.os}}-yarn-${{hashFiles('**/yarn.lock')}}
          restore-keys: |
            ${{runner.os}}-yarn-

      - run: corepack yarn install --immutable
      - run: corepack yarn build # We need the stubs to run the tests

      - run: corepack yarn test
        env:
          NOCK_ENV: replay
